version: '{build}'

image: Visual Studio 2017

build_script:
  - ps: |
      $outpath = (Get-Location).Path

      Set-Location C:\Tools\vcpkg
      git fetch origin pull/12877/head:test  2> $null
      git checkout test 2> $null
      bootstrap-vcpkg.bat
      if ($lastExitCode -ne 0) { throw "Failed to update vcpkg" }

      vcpkg install zlib --cmake-args="--trace-expand -DPORT_DEBUG=ON"
      Write-Host "Writing out package directory contents..."
      ls -r C:\tools\vcpkg\packages\zlib_x86-windows-port-debug

on_finish:
  - ps: |
      $blockRdp = $true;
      iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


artifacts:
  - path: devlibs.zip
