version: '{build}'

image: Visual Studio 2017

build_script:
  - ps: |
      $outpath = (Get-Location).Path

      Set-Location C:\tools\vcpkg
      git pull 2> $null
      git config user.email "nobody@nowhere.com"
      git config user.name "Nobody"
      git revert --no-edit 12c6dc5230785f93870a849712841b2ec707544f
      if ($lastExitCode -ne 0) { throw "Failed to back out openal-soft changes" }
      bootstrap-vcpkg.bat
      if ($lastExitCode -ne 0) { throw "Failed to update vcpkg" }
      vcpkg install openal-soft --triplet x86-windows
      Get-Content C:\tools\vcpkg\buildtrees\openal-soft\install-x86-windows-dbg-out.log
      if ($lastExitCode -ne 0) { throw "Failed to build static libs" }
