version: '{build}'

image: Visual Studio 2017

build_script:
  - ps: |
      $outpath = (Get-Location).Path

      Set-Location C:\tools\vcpkg
      git pull 2> $null
      bootstrap-vcpkg.bat
      if ($lastExitCode -ne 0) { throw "Failed to update vcpkg" }
      vcpkg install openal-soft --triplet x86-windows
      Get-Content C:\tools\vcpkg\buildtrees\openal-soft\install-x86-windows-dbg-out.log
      if ($lastExitCode -ne 0) { throw "Failed to build static libs" }
