version: '{build}'

image: Visual Studio 2017

build_script:
  - ps: |
      $outpath = (Get-Location).Path

      Set-Location C:\Tools\vcpkg
      git pull 2> $null
      bootstrap-vcpkg.bat
      if ($lastExitCode -ne 0) { throw "Failed to update vcpkg" }
      vcpkg install curl[sspi] expat freetype libjpeg-turbo libogg libpng `
          libvorbis libvpx openal-soft openssl opus pcre physx python2 python3 `
          speex string-theory zlib --triplet x86-windows-static-md
      if ($lastExitCode -ne 0) { throw "Failed to build static libs" }

      vcpkg list --x-full-desc

      # CURL's cmake modules are incompatible with Plasma, but CMake 3.17 tries
      # to use them anyway...  So we just nuke 'em
      Set-Location C:\tools\vcpkg\installed
      Remove-Item "x86-windows-static-md\share\curl\CURL*.cmake"

      Set-Location C:\tools\vcpkg\installed\x86-windows-static-md
      7z a $outpath\devlibs.zip debug\lib include lib misc share
      if ($lastExitCode -ne 0) { throw "Failed to archive static libs" }

artifacts:
  - path: devlibs.zip
